[package]
name = "game-net"
version = "0.1.0"
edition = "2024"

[dependencies]
game = { path = "../game", features = ["serde"] }
defmt = { version = "1.1.0", features = [], optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

[features]
default = []
defmt = ["dep:defmt"]
serde = ["dep:serde"]
