[build]
target = "thumbv8m.main-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load --update --verify --execute -t elf"
linker = "flip-link"

[env]
DEFMT_LOG = "debug"
WIFI_SSID = ""
WIFI_PASSWORD = ""