[package]
name = "hmi"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hydrate"
required-features = ["hydration"]

[features]
hydration = ["yew/hydration"]

[dependencies]
yew = { version = "0.23.0", features = ["csr"] }
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
uuid = { version = "1.23.2", features = ["serde"] }
futures = { version = "0.3.34", default-features = false }
web-sys = { version = "0.3.105" }
gloo-net = { version = "0.7.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.78"
tracing-web = "0.1.3"
tracing-subscriber = { version = "0.3.23", features = ["fmt"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "fs"] }
axum = { version = "0.8.9" }
tower-http = { version = "0.7.1", features = ["fs", "cors"] }

[dev-dependencies]
yew = { version = "0.23.0", features = ["hydration"] }